language: ruby
sudo: false
before_install:
  - gem update --system 3.0.3
  - gem install bundler:2.0.1
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2
  - jruby-9.1.17.0
  - jruby-9.2.6.0
branches:
  only:
    - master
cache: bundler
